### ISSUE TITLE
plugin not working for me

### ISSUE THREAD

**Issue by abhayastudios** [triniwiz/nativescript-videorecorder#7]
I am trying to use the plugin and it seems both on iOS and on Android it is not working for me. I installed the plugin and tried both requiring the module javascript style like in the docs and also changing it to import typescript style as below:

```
import {VideoRecorder as VR} from "nativescript-videorecorder";
let vr = new VR();
vr.record({
    saveToGallery:true, //default false | optional
    duration:30, //(seconds) default no limit | optional
    size:10, //(MB) default none | optional #android
    hd:true, //default  false low res | optional
    explanation:"Why do i need this permission" //optional on api 23 #android
})
.then((data)=>{
    console.log(data.file)
})
.catch((err)=>{
    console.log(err)
})
```

Any idea what may be wrong?

Android:

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Fail to load module: /data/data/org.nativescript.my-app/files/app/main.js

TypeError: Cannot read property 'getPackageName' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
  Frame: function:'', file:'/data/data/org.nativescript.my-app/files/app/tns_modules/nativescript-videorecorder/videorecorder.js', line: 12, column: 38
  Frame: function:'require', file:'', line: 1, column: 266
  Frame: function:'', file:'/data/data/org.nativescript.my-app/files/app/app.component.js', line: 3, column: 10
  Frame: function:'require', file:'', line: 1, column: 266
  Frame: function:'', file:'/data/data/org.nativescript.my-app/files/app/main.js', line: 4, column: 23
  Frame: function:'require', file:'', line: 1, column: 266


  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5116)
  at android.app.ActivityThread.access$1600(ActivityThread.java:177)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:5942)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: com.tns.NativeScriptException: 
Fail to load module: /data/data/org.nativescript.my-app/files/app/main.js

TypeError: Cannot read property 'getPackageName' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
  Frame: function:'', file:'/data/data/org.nativescript.my-app/files/app/tns_modules/nativescript-videorecorder/videorecorder.js', line: 12, column: 38
  Frame: function:'require', file:'', line: 1, column: 266
  Frame: function:'', file:'/data/data/org.nativescript.my-app/files/app/app.component.js', line: 3, column: 10
  Frame: function:'require', file:'', line: 1, column: 266
  Frame: function:'', file:'/data/data/org.nativescript.my-app/files/app/main.js', line: 4, column: 23
  Frame: function:'require', file:'', line: 1, column: 266


  at com.tns.Runtime.runModule(Native Method)
  at com.tns.Runtime.runModule(Runtime.java:241)
  at com.tns.Runtime.run(Runtime.java:235)
  at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5113)
  ... 9 more
```

iOS:

```
Jul 16 18:23:33 localhost my-app[37101]: *** JavaScript call stack:
  (
    0   UIApplicationMain@[native code]
    1   start@file:///app/tns_modules/application/application.js:233:26
    2   @file:///app/tns_modules/nativescript-angular/application.js:153:26
    3   ZoneAwarePromise@file:///app/tns_modules/zone.js/dist/zone-node.js:542:38
    4   nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:151:23
    5   anonymous@file:///app/main.js:5:36
    6   evaluate@[native code]
    7   moduleEvaluation@:1:11
    8   @:8:48
    9   promiseReactionJob@:1:11
  )
Jul 16 18:23:33 localhost my-app[37101]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'videoCameraImage must be either video or audio'
  *** First throw call stack:
  (
    0   CoreFoundation                      0x03853494 __exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x0330de02 objc_exception_throw + 50
    2   CoreFoundation                      0x038533bd +[NSException raise:format:] + 141
    3   PhotoLibrary                        0x18903472 -[PLVideoView initWithFrame:videoCameraImage:orientation:] + 192
    4   PhotoLibrary                        0x188febcb -[PLUIImageViewController loadView] + 1787
    5   PhotoLibrary                        0x18924f48 -[PLUIEditVideoViewController loadView] + 51
    6   UIKit                               0x016ca1c4 -[UIViewController loadViewIfRequired] + 154
    7   UIKit                               0x017162bb -[UINavigationController _layoutViewController:] + 52
    8   UIKit                               0x01716b75 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 421
    9   UIKit                               0x01716d1c -[UINavigationController _startTransition:fromViewController:toViewController:] + 145
    10  UIKit                               0x01718118 -[UINavigationController _startDeferredTransitionIfNeeded:] + 1038
    11  UIKit                               0x0171b073 -[UINavigationController pushViewController:transition:forceImmediate:] + 2354
    12  UIKit                               0x0171a5a9 __54-[UINavigationController pushViewController:animated:]_block_invoke + 491
    13  UIKit                               0x0171a613 __54-[UINavigationController pushViewController:animated:]_block_invoke1608 + 26
    14  UIKit                               0x016dad49 +[UIViewController _performWithoutDeferringTransitions:] + 117
    15  UIKit                               0x0171a24a -[UINavigationController pushViewController:animated:] + 483
    16  UIKit                               0x01b5f794 -[UIVideoEditorController _setupControllers] + 141
    17  UIKit                               0x01b5f308 -[UIVideoEditorController viewWillAppear:] + 62
    18  UIKit                               0x016d05fb -[UIViewController _setViewAppearState:isAnimating:] + 659
    19  UIKit                               0x016d0ceb -[UIViewController __viewWillAppear:] + 147
    20  UIKit                               0x016f3e45 -[UIViewController(UIContainerViewControllerProtectedMethods) beginAppearanceTransition:animated:] + 202
    21  UIKit                               0x01697eee __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 1115
    22  UIKit                               0x016dae3b __40+[UIViewController _scheduleTransition:]_block_invoke + 18
    23  UIKit                               0x015077cb _runAfterCACommitDeferredBlocks + 337
    24  UIKit                               0x0151da60 _cleanUpAfterCAFlushAndRunDeferredBlocks + 103
    25  UIKit                               0x0152bef6 _afterCACommitHandler + 102
    26  CoreFoundation                      0x0376575e __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 30
    27  CoreFoundation                      0x037656be __CFRunLoopDoObservers + 398
    28  CoreFoundation                      0x0375b03c __CFRunLoopRun + 1340
    29  CoreFoundation                      0x0375a846 CFRunLoopRunSpecific + 470
    30  CoreFoundation                      0x0375a65b CFRunLoopRunInMode + 123
    31  GraphicsServices                    0x054ca664 GSEventRunModal + 192
    32  GraphicsServices                    0x054ca4a1 GSEventRun + 104
    33  UIKit                               0x014f9eb9 UIApplicationMain + 160
    34  NativeScript                        0x00afdee8 ffi_call_i386 + 24
  )
```

**Comment by triniwiz** [comment]
android & ios versions ?

**Comment by abhayastudios** [comment]
I tried on a physical Android device v5.0.1 and on iOS v9.3 simulator that comes with Xcode. Also I do see these directories so it seems the build/prepare steps did pick up on the plugin:

```
./node_modules/nativescript-videorecorder
./platforms/android/build/intermediates/assets/F0/debug/app/tns_modules/nativescript-videorecorder
./platforms/android/src/main/assets/app/tns_modules/nativescript-videorecorder
./platforms/ios/build/emulator/my-app.app/app/tns_modules/nativescript-videorecorder
./platforms/ios/my-app/app/tns_modules/nativescript-videorecorder
```

**Comment by triniwiz** [comment]
I wanted the version so i can try to reproduce on android but @victorsosa takes care of ios

**Comment by abhayastudios** [comment]
Thanks! I am probably missing something basic in the setup. I am new to Nativescript...

**Comment by triniwiz** [comment]
@abhayastudios you can try updating the plugin to `1.3.1` the android problem should be fixed

**Comment by abhayastudios** [comment]
Android seems to work now :) Just the iOS issue remains.

Thanks!

**Comment by mattrwh-pC506** [comment]
@triniwiz and @victorsosa I'm also seeing the same exception with ios (android is working). 

`reason: 'videoCameraImage must be either video or audio'`

The ios version I'm emulating on is 9.3.

**Comment by Daxito** [comment]
So, iOS is still not supported :-s

**Comment by triniwiz** [comment]
it is supported just needs a patch

**Comment by victorsosa** [comment]
I haven't had time, sorry

**Comment by Daxito** [comment]
Thank you @triniwiz @victorsosa ,I will keep an eye on this plugin!

**Comment by tastypwnda** [comment]
Hello @triniwiz @victorsosa. We would like to use your plugin in one of our projects but unfortunately iOS-support is still not provided. We would like to get with you in touch with you and eventually pay for the fix (or provide help, if you don't plan fixing it sooner or later). Kind Regards Dominik D. (team-nifty.com)

**Comment by victorsosa** [comment]
@abhayastudios It's not possible to access camera of your development machine to be used as simulator camera. Camera functionality is not available in any iOS version and any Simulator. You will have to use device only for testing camera purpose.

**Comment by carlkibler** [comment]
Along with @tastypwnda, I would contribute some money to getting iOS operational again. The plugin is great on Android but I'd sure like my app to work on iOS as well.

**Comment by tastypwnda** [comment]
@triniwiz - I still want to get in touch with you. Our product is nearly in production and the only feature still not working is the video recording. We need support and are willing to contribute some money for the fix. Please let me at least know if you are still working on it. 3 months since the last commit is fairly long.

**Comment by tastypwnda** [comment]
Could you please give an update on the current development status. Still waiting for a reply.

**Comment by victorsosa** [comment]
To complete the develop and test this, an ipad is needed and also a macbook to compile the project on a OS X environment, and right now I don't have the resources. Camera functionality is not available in any Simulator. I can borrow an Ipad mini, but still missing the macbook. That's why I couldn't fix it, right now.

**Comment by triniwiz** [comment]
Same here i am waiting until the after the apple event month end before i purchase a macbook but i do have an ipad already

**Comment by tastypwnda** [comment]
We have all the resources needed to help you. Is it possible to chat or get in touch with you? (teamspeak or skype?) We could help you finish and test the code and you can publish it. We have all the hardware necessary.

**Comment by AresDev** [comment]
¿Any progress?

If I run it from XCode I get "videoCameraImage must be either video or audio" error

**Comment by developper89** [comment]
hello @tastypwnda , did you find someone for the ios camera functionality ?

**Comment by 1392324000** [comment]
@abhayastudios Can U share how did U deal with the peoblem ? :-)

**Comment by triniwiz** [comment]
iOS fix coming very soon the basic recording features work already on my machine I'm just working on some advanced features before I push the new build

**Comment by triniwiz** [comment]
Ok so everything should be working in the latest version upgrade away and feel free to reopen if things go south
